### ISSUE TITLE
Incorrectly Named Function

### ISSUE THREAD

**Issue by CaptainChris425** [alexraskin/lhbot#1]
# Title: Incorrectly Named Function
## Description:
Function is not named correctly

## Expected
```
@commands.command(name="egirl")
    async def egirl(self, ctx):
```
## Actual
```
@commands.command(name="egirl")
    async def dva(self, ctx):
```
##Line
https://github.com/alexraskin/lhbot/blob/7704e2a99f388fc60befcc241f5dbf7fd1e5b0bb/cogs/lhcloudy.py#L120

**Comment by alexraskin** [comment]
Fix in this [PR](https://github.com/alexraskin/lhbot/pull/3)
