### ISSUE TITLE
Incorrectly Named Function

### ISSUE THREAD

**Issue by CaptainChris425** [alexraskin/lhbot#2]
# Title: Incorrectly Named Function
## Description:
Function is not named correctly

## Expected
```
@commands.command(name="dva2")
    async def dva2(self, ctx):
```
```
@commands.command(name="dva3")
    async def dva3(self, ctx):
```
## Actual
```
@commands.command(name="dva2")
    async def dva(self, ctx):
```
```
@commands.command(name="dva2")
    async def dva(self, ctx):
```
##Line
https://github.com/alexraskin/lhbot/blob/7704e2a99f388fc60befcc241f5dbf7fd1e5b0bb/cogs/lhcloudy.py#L105
https://github.com/alexraskin/lhbot/blob/7704e2a99f388fc60befcc241f5dbf7fd1e5b0bb/cogs/lhcloudy.py#L113

**Comment by alexraskin** [comment]
Fix in this [PR](https://github.com/alexraskin/lhbot/pull/3) Thanks Chris
