### ISSUE TITLE
Non LH guesses can be entered

### ISSUE THREAD

**Issue by CaptainChris425** [alexraskin/lhbot#7]
# Title: Non LH guesses can be entered. 

## Description  
When guessing what LH stands for users are able to enter guesses what do not start with L and H.  

## Priority
Low

## Suggestion
1. Regex - https://docs.python.org/3/library/re.html  
Ex: ```^[Ll].*[ ][Hh].*``` *First draft regex match starting with L then containing space before an H*  

1. Try/Catch 
Probably an easier way. 

Try splitting the words and checking if first letters are L and H. Handle any error by replying with some "bad guess" message. 
```
try: 
    words = guess.split(' ') 
    If word[0][0].toLower() is not 'l' : throw Exception
    If word[1][0].toLower() is not 'h': throw Exception
catch Exception ex: 
    ...
    Send discord message
    ....
```

https://github.com/alexraskin/lhbot/blob/81f37c5774f08b205cad0815bd7c2c0bc7c6fee6/cogs/lhguess.py#L70

**Comment by alexraskin** [comment]
Hey @CaptainChris425 I went ahead and added a `startswith("l")`. This will just check if user passed a guess that starts with `l`. Thanks for the opening this!

https://github.com/alexraskin/lhbot/blob/b1ff1af15c5abf26c4fc8c540d840761d723eb40/cogs/lhguess.py#L64

**Comment by CaptainChris425** [comment]
Good change.
